# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ajian/work/chatroom

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ajian/work/chatroom

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ajian/work/chatroom/CMakeFiles /home/ajian/work/chatroom//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ajian/work/chatroom/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named client.out

# Build rule for target.
client.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 client.out
.PHONY : client.out

# fast build rule for target.
client.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/build
.PHONY : client.out/fast

#=============================================================================
# Target rules for targets named server.out

# Build rule for target.
server.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server.out
.PHONY : server.out

# fast build rule for target.
server.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/build
.PHONY : server.out/fast

src/client_event.o: src/client_event.c.o
.PHONY : src/client_event.o

# target to build an object file
src/client_event.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/client_event.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/client_event.c.o
.PHONY : src/client_event.c.o

src/client_event.i: src/client_event.c.i
.PHONY : src/client_event.i

# target to preprocess a source file
src/client_event.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/client_event.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/client_event.c.i
.PHONY : src/client_event.c.i

src/client_event.s: src/client_event.c.s
.PHONY : src/client_event.s

# target to generate assembly for a file
src/client_event.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/client_event.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/client_event.c.s
.PHONY : src/client_event.c.s

src/creat_daemon.o: src/creat_daemon.c.o
.PHONY : src/creat_daemon.o

# target to build an object file
src/creat_daemon.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/creat_daemon.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/creat_daemon.c.o
.PHONY : src/creat_daemon.c.o

src/creat_daemon.i: src/creat_daemon.c.i
.PHONY : src/creat_daemon.i

# target to preprocess a source file
src/creat_daemon.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/creat_daemon.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/creat_daemon.c.i
.PHONY : src/creat_daemon.c.i

src/creat_daemon.s: src/creat_daemon.c.s
.PHONY : src/creat_daemon.s

# target to generate assembly for a file
src/creat_daemon.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/creat_daemon.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/creat_daemon.c.s
.PHONY : src/creat_daemon.c.s

src/epoll_add.o: src/epoll_add.c.o
.PHONY : src/epoll_add.o

# target to build an object file
src/epoll_add.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/epoll_add.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/epoll_add.c.o
.PHONY : src/epoll_add.c.o

src/epoll_add.i: src/epoll_add.c.i
.PHONY : src/epoll_add.i

# target to preprocess a source file
src/epoll_add.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/epoll_add.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/epoll_add.c.i
.PHONY : src/epoll_add.c.i

src/epoll_add.s: src/epoll_add.c.s
.PHONY : src/epoll_add.s

# target to generate assembly for a file
src/epoll_add.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/epoll_add.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/epoll_add.c.s
.PHONY : src/epoll_add.c.s

src/epoll_init_lfd.o: src/epoll_init_lfd.c.o
.PHONY : src/epoll_init_lfd.o

# target to build an object file
src/epoll_init_lfd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/epoll_init_lfd.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/epoll_init_lfd.c.o
.PHONY : src/epoll_init_lfd.c.o

src/epoll_init_lfd.i: src/epoll_init_lfd.c.i
.PHONY : src/epoll_init_lfd.i

# target to preprocess a source file
src/epoll_init_lfd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/epoll_init_lfd.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/epoll_init_lfd.c.i
.PHONY : src/epoll_init_lfd.c.i

src/epoll_init_lfd.s: src/epoll_init_lfd.c.s
.PHONY : src/epoll_init_lfd.s

# target to generate assembly for a file
src/epoll_init_lfd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/epoll_init_lfd.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/epoll_init_lfd.c.s
.PHONY : src/epoll_init_lfd.c.s

src/epoll_set.o: src/epoll_set.c.o
.PHONY : src/epoll_set.o

# target to build an object file
src/epoll_set.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/epoll_set.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/epoll_set.c.o
.PHONY : src/epoll_set.c.o

src/epoll_set.i: src/epoll_set.c.i
.PHONY : src/epoll_set.i

# target to preprocess a source file
src/epoll_set.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/epoll_set.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/epoll_set.c.i
.PHONY : src/epoll_set.c.i

src/epoll_set.s: src/epoll_set.c.s
.PHONY : src/epoll_set.s

# target to generate assembly for a file
src/epoll_set.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/epoll_set.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/epoll_set.c.s
.PHONY : src/epoll_set.c.s

src/event_del.o: src/event_del.c.o
.PHONY : src/event_del.o

# target to build an object file
src/event_del.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/event_del.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/event_del.c.o
.PHONY : src/event_del.c.o

src/event_del.i: src/event_del.c.i
.PHONY : src/event_del.i

# target to preprocess a source file
src/event_del.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/event_del.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/event_del.c.i
.PHONY : src/event_del.c.i

src/event_del.s: src/event_del.c.s
.PHONY : src/event_del.s

# target to generate assembly for a file
src/event_del.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/event_del.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/event_del.c.s
.PHONY : src/event_del.c.s

src/justwrite.o: src/justwrite.c.o
.PHONY : src/justwrite.o

# target to build an object file
src/justwrite.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/justwrite.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/justwrite.c.o
.PHONY : src/justwrite.c.o

src/justwrite.i: src/justwrite.c.i
.PHONY : src/justwrite.i

# target to preprocess a source file
src/justwrite.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/justwrite.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/justwrite.c.i
.PHONY : src/justwrite.c.i

src/justwrite.s: src/justwrite.c.s
.PHONY : src/justwrite.s

# target to generate assembly for a file
src/justwrite.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/justwrite.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/justwrite.c.s
.PHONY : src/justwrite.c.s

src/lfdaccept.o: src/lfdaccept.c.o
.PHONY : src/lfdaccept.o

# target to build an object file
src/lfdaccept.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/lfdaccept.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/lfdaccept.c.o
.PHONY : src/lfdaccept.c.o

src/lfdaccept.i: src/lfdaccept.c.i
.PHONY : src/lfdaccept.i

# target to preprocess a source file
src/lfdaccept.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/lfdaccept.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/lfdaccept.c.i
.PHONY : src/lfdaccept.c.i

src/lfdaccept.s: src/lfdaccept.c.s
.PHONY : src/lfdaccept.s

# target to generate assembly for a file
src/lfdaccept.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/lfdaccept.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/lfdaccept.c.s
.PHONY : src/lfdaccept.c.s

src/my_zlog_init.o: src/my_zlog_init.c.o
.PHONY : src/my_zlog_init.o

# target to build an object file
src/my_zlog_init.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/my_zlog_init.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/my_zlog_init.c.o
.PHONY : src/my_zlog_init.c.o

src/my_zlog_init.i: src/my_zlog_init.c.i
.PHONY : src/my_zlog_init.i

# target to preprocess a source file
src/my_zlog_init.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/my_zlog_init.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/my_zlog_init.c.i
.PHONY : src/my_zlog_init.c.i

src/my_zlog_init.s: src/my_zlog_init.c.s
.PHONY : src/my_zlog_init.s

# target to generate assembly for a file
src/my_zlog_init.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/my_zlog_init.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/my_zlog_init.c.s
.PHONY : src/my_zlog_init.c.s

src/serverhelp.o: src/serverhelp.c.o
.PHONY : src/serverhelp.o

# target to build an object file
src/serverhelp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/serverhelp.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/serverhelp.c.o
.PHONY : src/serverhelp.c.o

src/serverhelp.i: src/serverhelp.c.i
.PHONY : src/serverhelp.i

# target to preprocess a source file
src/serverhelp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/serverhelp.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/serverhelp.c.i
.PHONY : src/serverhelp.c.i

src/serverhelp.s: src/serverhelp.c.s
.PHONY : src/serverhelp.s

# target to generate assembly for a file
src/serverhelp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/serverhelp.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/serverhelp.c.s
.PHONY : src/serverhelp.c.s

src/setconfig.o: src/setconfig.c.o
.PHONY : src/setconfig.o

# target to build an object file
src/setconfig.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/setconfig.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/setconfig.c.o
.PHONY : src/setconfig.c.o

src/setconfig.i: src/setconfig.c.i
.PHONY : src/setconfig.i

# target to preprocess a source file
src/setconfig.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/setconfig.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/setconfig.c.i
.PHONY : src/setconfig.c.i

src/setconfig.s: src/setconfig.c.s
.PHONY : src/setconfig.s

# target to generate assembly for a file
src/setconfig.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/setconfig.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/setconfig.c.s
.PHONY : src/setconfig.c.s

src/showevents.o: src/showevents.c.o
.PHONY : src/showevents.o

# target to build an object file
src/showevents.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/showevents.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/showevents.c.o
.PHONY : src/showevents.c.o

src/showevents.i: src/showevents.c.i
.PHONY : src/showevents.i

# target to preprocess a source file
src/showevents.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/showevents.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/showevents.c.i
.PHONY : src/showevents.c.i

src/showevents.s: src/showevents.c.s
.PHONY : src/showevents.s

# target to generate assembly for a file
src/showevents.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/showevents.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/showevents.c.s
.PHONY : src/showevents.c.s

src/wrap.o: src/wrap.c.o
.PHONY : src/wrap.o

# target to build an object file
src/wrap.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/wrap.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/wrap.c.o
.PHONY : src/wrap.c.o

src/wrap.i: src/wrap.c.i
.PHONY : src/wrap.i

# target to preprocess a source file
src/wrap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/wrap.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/wrap.c.i
.PHONY : src/wrap.c.i

src/wrap.s: src/wrap.c.s
.PHONY : src/wrap.s

# target to generate assembly for a file
src/wrap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.out.dir/build.make CMakeFiles/client.out.dir/src/wrap.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/src/wrap.c.s
.PHONY : src/wrap.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... client.out"
	@echo "... server.out"
	@echo "... src/client_event.o"
	@echo "... src/client_event.i"
	@echo "... src/client_event.s"
	@echo "... src/creat_daemon.o"
	@echo "... src/creat_daemon.i"
	@echo "... src/creat_daemon.s"
	@echo "... src/epoll_add.o"
	@echo "... src/epoll_add.i"
	@echo "... src/epoll_add.s"
	@echo "... src/epoll_init_lfd.o"
	@echo "... src/epoll_init_lfd.i"
	@echo "... src/epoll_init_lfd.s"
	@echo "... src/epoll_set.o"
	@echo "... src/epoll_set.i"
	@echo "... src/epoll_set.s"
	@echo "... src/event_del.o"
	@echo "... src/event_del.i"
	@echo "... src/event_del.s"
	@echo "... src/justwrite.o"
	@echo "... src/justwrite.i"
	@echo "... src/justwrite.s"
	@echo "... src/lfdaccept.o"
	@echo "... src/lfdaccept.i"
	@echo "... src/lfdaccept.s"
	@echo "... src/my_zlog_init.o"
	@echo "... src/my_zlog_init.i"
	@echo "... src/my_zlog_init.s"
	@echo "... src/serverhelp.o"
	@echo "... src/serverhelp.i"
	@echo "... src/serverhelp.s"
	@echo "... src/setconfig.o"
	@echo "... src/setconfig.i"
	@echo "... src/setconfig.s"
	@echo "... src/showevents.o"
	@echo "... src/showevents.i"
	@echo "... src/showevents.s"
	@echo "... src/wrap.o"
	@echo "... src/wrap.i"
	@echo "... src/wrap.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

