# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ajian/work/cpptest/items/big_items/linuxc/chatroom

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ajian/work/cpptest/items/big_items/linuxc/chatroom

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ajian/work/cpptest/items/big_items/linuxc/chatroom/CMakeFiles /home/ajian/work/cpptest/items/big_items/linuxc/chatroom//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ajian/work/cpptest/items/big_items/linuxc/chatroom/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named server.out

# Build rule for target.
server.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server.out
.PHONY : server.out

# fast build rule for target.
server.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/build
.PHONY : server.out/fast

rely/func/client_event.o: rely/func/client_event.c.o
.PHONY : rely/func/client_event.o

# target to build an object file
rely/func/client_event.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/client_event.c.o
.PHONY : rely/func/client_event.c.o

rely/func/client_event.i: rely/func/client_event.c.i
.PHONY : rely/func/client_event.i

# target to preprocess a source file
rely/func/client_event.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/client_event.c.i
.PHONY : rely/func/client_event.c.i

rely/func/client_event.s: rely/func/client_event.c.s
.PHONY : rely/func/client_event.s

# target to generate assembly for a file
rely/func/client_event.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/client_event.c.s
.PHONY : rely/func/client_event.c.s

rely/func/creat_daemon.o: rely/func/creat_daemon.c.o
.PHONY : rely/func/creat_daemon.o

# target to build an object file
rely/func/creat_daemon.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/creat_daemon.c.o
.PHONY : rely/func/creat_daemon.c.o

rely/func/creat_daemon.i: rely/func/creat_daemon.c.i
.PHONY : rely/func/creat_daemon.i

# target to preprocess a source file
rely/func/creat_daemon.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/creat_daemon.c.i
.PHONY : rely/func/creat_daemon.c.i

rely/func/creat_daemon.s: rely/func/creat_daemon.c.s
.PHONY : rely/func/creat_daemon.s

# target to generate assembly for a file
rely/func/creat_daemon.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/creat_daemon.c.s
.PHONY : rely/func/creat_daemon.c.s

rely/func/epoll_add.o: rely/func/epoll_add.c.o
.PHONY : rely/func/epoll_add.o

# target to build an object file
rely/func/epoll_add.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/epoll_add.c.o
.PHONY : rely/func/epoll_add.c.o

rely/func/epoll_add.i: rely/func/epoll_add.c.i
.PHONY : rely/func/epoll_add.i

# target to preprocess a source file
rely/func/epoll_add.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/epoll_add.c.i
.PHONY : rely/func/epoll_add.c.i

rely/func/epoll_add.s: rely/func/epoll_add.c.s
.PHONY : rely/func/epoll_add.s

# target to generate assembly for a file
rely/func/epoll_add.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/epoll_add.c.s
.PHONY : rely/func/epoll_add.c.s

rely/func/epoll_init_lfd.o: rely/func/epoll_init_lfd.c.o
.PHONY : rely/func/epoll_init_lfd.o

# target to build an object file
rely/func/epoll_init_lfd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/epoll_init_lfd.c.o
.PHONY : rely/func/epoll_init_lfd.c.o

rely/func/epoll_init_lfd.i: rely/func/epoll_init_lfd.c.i
.PHONY : rely/func/epoll_init_lfd.i

# target to preprocess a source file
rely/func/epoll_init_lfd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/epoll_init_lfd.c.i
.PHONY : rely/func/epoll_init_lfd.c.i

rely/func/epoll_init_lfd.s: rely/func/epoll_init_lfd.c.s
.PHONY : rely/func/epoll_init_lfd.s

# target to generate assembly for a file
rely/func/epoll_init_lfd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/epoll_init_lfd.c.s
.PHONY : rely/func/epoll_init_lfd.c.s

rely/func/epoll_set.o: rely/func/epoll_set.c.o
.PHONY : rely/func/epoll_set.o

# target to build an object file
rely/func/epoll_set.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/epoll_set.c.o
.PHONY : rely/func/epoll_set.c.o

rely/func/epoll_set.i: rely/func/epoll_set.c.i
.PHONY : rely/func/epoll_set.i

# target to preprocess a source file
rely/func/epoll_set.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/epoll_set.c.i
.PHONY : rely/func/epoll_set.c.i

rely/func/epoll_set.s: rely/func/epoll_set.c.s
.PHONY : rely/func/epoll_set.s

# target to generate assembly for a file
rely/func/epoll_set.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/epoll_set.c.s
.PHONY : rely/func/epoll_set.c.s

rely/func/event_del.o: rely/func/event_del.c.o
.PHONY : rely/func/event_del.o

# target to build an object file
rely/func/event_del.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/event_del.c.o
.PHONY : rely/func/event_del.c.o

rely/func/event_del.i: rely/func/event_del.c.i
.PHONY : rely/func/event_del.i

# target to preprocess a source file
rely/func/event_del.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/event_del.c.i
.PHONY : rely/func/event_del.c.i

rely/func/event_del.s: rely/func/event_del.c.s
.PHONY : rely/func/event_del.s

# target to generate assembly for a file
rely/func/event_del.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/event_del.c.s
.PHONY : rely/func/event_del.c.s

rely/func/justwrite.o: rely/func/justwrite.c.o
.PHONY : rely/func/justwrite.o

# target to build an object file
rely/func/justwrite.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/justwrite.c.o
.PHONY : rely/func/justwrite.c.o

rely/func/justwrite.i: rely/func/justwrite.c.i
.PHONY : rely/func/justwrite.i

# target to preprocess a source file
rely/func/justwrite.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/justwrite.c.i
.PHONY : rely/func/justwrite.c.i

rely/func/justwrite.s: rely/func/justwrite.c.s
.PHONY : rely/func/justwrite.s

# target to generate assembly for a file
rely/func/justwrite.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/justwrite.c.s
.PHONY : rely/func/justwrite.c.s

rely/func/lfdaccept.o: rely/func/lfdaccept.c.o
.PHONY : rely/func/lfdaccept.o

# target to build an object file
rely/func/lfdaccept.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/lfdaccept.c.o
.PHONY : rely/func/lfdaccept.c.o

rely/func/lfdaccept.i: rely/func/lfdaccept.c.i
.PHONY : rely/func/lfdaccept.i

# target to preprocess a source file
rely/func/lfdaccept.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/lfdaccept.c.i
.PHONY : rely/func/lfdaccept.c.i

rely/func/lfdaccept.s: rely/func/lfdaccept.c.s
.PHONY : rely/func/lfdaccept.s

# target to generate assembly for a file
rely/func/lfdaccept.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/lfdaccept.c.s
.PHONY : rely/func/lfdaccept.c.s

rely/func/log.o: rely/func/log.c.o
.PHONY : rely/func/log.o

# target to build an object file
rely/func/log.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/log.c.o
.PHONY : rely/func/log.c.o

rely/func/log.i: rely/func/log.c.i
.PHONY : rely/func/log.i

# target to preprocess a source file
rely/func/log.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/log.c.i
.PHONY : rely/func/log.c.i

rely/func/log.s: rely/func/log.c.s
.PHONY : rely/func/log.s

# target to generate assembly for a file
rely/func/log.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/log.c.s
.PHONY : rely/func/log.c.s

rely/func/my_zlog_init.o: rely/func/my_zlog_init.c.o
.PHONY : rely/func/my_zlog_init.o

# target to build an object file
rely/func/my_zlog_init.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/my_zlog_init.c.o
.PHONY : rely/func/my_zlog_init.c.o

rely/func/my_zlog_init.i: rely/func/my_zlog_init.c.i
.PHONY : rely/func/my_zlog_init.i

# target to preprocess a source file
rely/func/my_zlog_init.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/my_zlog_init.c.i
.PHONY : rely/func/my_zlog_init.c.i

rely/func/my_zlog_init.s: rely/func/my_zlog_init.c.s
.PHONY : rely/func/my_zlog_init.s

# target to generate assembly for a file
rely/func/my_zlog_init.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/my_zlog_init.c.s
.PHONY : rely/func/my_zlog_init.c.s

rely/func/serverhelp.o: rely/func/serverhelp.c.o
.PHONY : rely/func/serverhelp.o

# target to build an object file
rely/func/serverhelp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/serverhelp.c.o
.PHONY : rely/func/serverhelp.c.o

rely/func/serverhelp.i: rely/func/serverhelp.c.i
.PHONY : rely/func/serverhelp.i

# target to preprocess a source file
rely/func/serverhelp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/serverhelp.c.i
.PHONY : rely/func/serverhelp.c.i

rely/func/serverhelp.s: rely/func/serverhelp.c.s
.PHONY : rely/func/serverhelp.s

# target to generate assembly for a file
rely/func/serverhelp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/serverhelp.c.s
.PHONY : rely/func/serverhelp.c.s

rely/func/setconfig.o: rely/func/setconfig.c.o
.PHONY : rely/func/setconfig.o

# target to build an object file
rely/func/setconfig.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/setconfig.c.o
.PHONY : rely/func/setconfig.c.o

rely/func/setconfig.i: rely/func/setconfig.c.i
.PHONY : rely/func/setconfig.i

# target to preprocess a source file
rely/func/setconfig.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/setconfig.c.i
.PHONY : rely/func/setconfig.c.i

rely/func/setconfig.s: rely/func/setconfig.c.s
.PHONY : rely/func/setconfig.s

# target to generate assembly for a file
rely/func/setconfig.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/setconfig.c.s
.PHONY : rely/func/setconfig.c.s

rely/func/showevents.o: rely/func/showevents.c.o
.PHONY : rely/func/showevents.o

# target to build an object file
rely/func/showevents.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/showevents.c.o
.PHONY : rely/func/showevents.c.o

rely/func/showevents.i: rely/func/showevents.c.i
.PHONY : rely/func/showevents.i

# target to preprocess a source file
rely/func/showevents.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/showevents.c.i
.PHONY : rely/func/showevents.c.i

rely/func/showevents.s: rely/func/showevents.c.s
.PHONY : rely/func/showevents.s

# target to generate assembly for a file
rely/func/showevents.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/func/showevents.c.s
.PHONY : rely/func/showevents.c.s

rely/includec/wrap.o: rely/includec/wrap.c.o
.PHONY : rely/includec/wrap.o

# target to build an object file
rely/includec/wrap.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/includec/wrap.c.o
.PHONY : rely/includec/wrap.c.o

rely/includec/wrap.i: rely/includec/wrap.c.i
.PHONY : rely/includec/wrap.i

# target to preprocess a source file
rely/includec/wrap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/includec/wrap.c.i
.PHONY : rely/includec/wrap.c.i

rely/includec/wrap.s: rely/includec/wrap.c.s
.PHONY : rely/includec/wrap.s

# target to generate assembly for a file
rely/includec/wrap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/rely/includec/wrap.c.s
.PHONY : rely/includec/wrap.c.s

server/server.o: server/server.c.o
.PHONY : server/server.o

# target to build an object file
server/server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/server/server.c.o
.PHONY : server/server.c.o

server/server.i: server/server.c.i
.PHONY : server/server.i

# target to preprocess a source file
server/server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/server/server.c.i
.PHONY : server/server.c.i

server/server.s: server/server.c.s
.PHONY : server/server.s

# target to generate assembly for a file
server/server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.out.dir/build.make CMakeFiles/server.out.dir/server/server.c.s
.PHONY : server/server.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... server.out"
	@echo "... rely/func/client_event.o"
	@echo "... rely/func/client_event.i"
	@echo "... rely/func/client_event.s"
	@echo "... rely/func/creat_daemon.o"
	@echo "... rely/func/creat_daemon.i"
	@echo "... rely/func/creat_daemon.s"
	@echo "... rely/func/epoll_add.o"
	@echo "... rely/func/epoll_add.i"
	@echo "... rely/func/epoll_add.s"
	@echo "... rely/func/epoll_init_lfd.o"
	@echo "... rely/func/epoll_init_lfd.i"
	@echo "... rely/func/epoll_init_lfd.s"
	@echo "... rely/func/epoll_set.o"
	@echo "... rely/func/epoll_set.i"
	@echo "... rely/func/epoll_set.s"
	@echo "... rely/func/event_del.o"
	@echo "... rely/func/event_del.i"
	@echo "... rely/func/event_del.s"
	@echo "... rely/func/justwrite.o"
	@echo "... rely/func/justwrite.i"
	@echo "... rely/func/justwrite.s"
	@echo "... rely/func/lfdaccept.o"
	@echo "... rely/func/lfdaccept.i"
	@echo "... rely/func/lfdaccept.s"
	@echo "... rely/func/log.o"
	@echo "... rely/func/log.i"
	@echo "... rely/func/log.s"
	@echo "... rely/func/my_zlog_init.o"
	@echo "... rely/func/my_zlog_init.i"
	@echo "... rely/func/my_zlog_init.s"
	@echo "... rely/func/serverhelp.o"
	@echo "... rely/func/serverhelp.i"
	@echo "... rely/func/serverhelp.s"
	@echo "... rely/func/setconfig.o"
	@echo "... rely/func/setconfig.i"
	@echo "... rely/func/setconfig.s"
	@echo "... rely/func/showevents.o"
	@echo "... rely/func/showevents.i"
	@echo "... rely/func/showevents.s"
	@echo "... rely/includec/wrap.o"
	@echo "... rely/includec/wrap.i"
	@echo "... rely/includec/wrap.s"
	@echo "... server/server.o"
	@echo "... server/server.i"
	@echo "... server/server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

